### ISSUE TITLE
about RestoreFromSeed.java

### ISSUE THREAD

**Issue by mnock** [bitcoincash-wallet/bitcoincashj#11]
I'm a novice, and I'm very confused about this problem. When I test RestoreFromSeed.java, I found that when creationtime at last year or earlier, Chain download speed would be very slow. How do you recover a wallet that was generated in 2015 and get its historical transaction?Is it fast?
![Uploading $JRG0)V@8%I)FT1~0SV_43F.png…]()

**Comment by HashEngineering** [comment]
It will be slower when creation time is earlier.

**Comment by HashEngineering** [comment]
http://bitcoinj.cash/

This repo is obsolete.  See the above link.

**Comment by mnock** [comment]
If I got the 1bch 1 years ago, now I want to restore this wallet. Is creation time going to be set up 1 years ago? Otherwise I can't get the right balance of my wallet?

**Comment by HashEngineering** [comment]
Yes, the creation time needs to be set to a time before the first transaction.  Normally a Wallet app will set the creation time to when the seed is created.  However, the seed itself has no time stamp.

**Comment by mnock** [comment]
But it took me 10 minutes to recover transaction for a month. How can I get the balance quickly?

**Comment by HashEngineering** [comment]
Sounds like a lot of transactions.  I don’t know of a way to speed it up.
