### ISSUE TITLE
Address always changes. How do I use my address?

### ISSUE THREAD

**Issue by fastener** [bitcoincash-wallet/bitcoincashj#12]
String seedCode = "xxxxxx   xx";
	        DeterministicSeed seed = null;
	        long creationtime = 1524318335L;
	     		try {
	     			seed = new DeterministicSeed(seedCode, null, "", creationtime);
	     		} catch (UnreadableWalletException e) {
	     			// TODO Auto-generated catch block
	     			e.printStackTrace();
	     		}
	     	 wallet=Wallet.fromSeed(params, seed);
I use the above code to import my wallet, but when using the 

> wallet.currentReceiveAddress()

 code, the address sometimes suddenly becomes something else. How do I import the coin to my address and send it out?

**Comment by HashEngineering** [comment]
This repo is not being maintained.

https://github.com/bitcoinj-cash/bitcoinj/issues

The address returned by wallet.currentReceiveAddress will be changed when the current address has received a transaction.
