### ISSUE TITLE
Testnet - Send not working 

### ISSUE THREAD

**Issue by kunalransing** [bitcoincash-wallet/bitcoincashj#7]
When we send,  tx create as well as balance deduct from wallet but we don't find tx on testnet. For anyone,  send is working ?

**Comment by ethands** [comment]
Did you solve this problem? I have the same problem

**Comment by HashEngineering** [comment]
It was working for me, but note that this repo is no longer supported.  

See:  https://github.com/bitcoinj-cash/bitcoinj
